Faucard patch1
fau-fablab/FabLabKasse pull request #147
Opened 2017-05-02 20:29 UTC by BDrescher

Hey all,
as the current faucard payment occured errors in relation to the misuse of floating points precision, I've today tried to account all occurences of those and patch them. Additionally I have updated the log generation used for the invoice to be able to skip errors manually and made it a little safer.

@mgmax @patkan I would be happy if you got the time to review my changes and maybe point at code passages which are not yet safe enough.

2017-05-02 20:54 UTC, mgmax reviewed
Not sure whether we really want to change the database, because this will require some conversion work and cause trouble at other places.

2017-05-02 20:54 UTC, mgmax commented on FabLabKasse/faucardPayment/FAUcardPaymentThread.py
> +        self.amount = amount
Does amount have to be float? Passing it as Decimal would be cleaner.

2017-05-02 20:54 UTC, mgmax commented on FabLabKasse/faucardPayment/FAUcardPaymentThread.py
> +        self.amount = amount
Changing the meaning of `amount` from cents to euros is dangerous. Maybe just remove the old `amount` variable and only use amount_cents?

2017-05-02 20:54 UTC, mgmax commented on FabLabKasse/faucardPayment/MagPosLog.py
> +        self.cur.execute("CREATE TABLE IF NOT EXISTS MagPosLog(id INTEGER PRIMARY KEY AUTOINCREMENT, datum, cardnumber INT, amount TEXT, oldbalance INT, newbalance INT, timestamp_payed, status INT, i
SQLite cannot (?) change the value of a column, and conversion will be quite annoying. I think we should rather accept storing the values as float and load them with float_to_decimal. As long as you don't go above 1e8 euros or so, there is no problem with float as long as you round correctly.

If you really do want to convert the database, then we could just switch to INT and store it as cents.

2017-05-02 20:54 UTC, mgmax commented on FabLabKasse/faucardPayment/faucard.py
>          assert isinstance(amount, (Decimal, float)), "PayupFAUCard: Amount to pay not Decimal or float"
this line should be changed, as we only want to accept Decimal (?)

2017-05-02 20:54 UTC, mgmax commented on FabLabKasse/faucardPayment/generateLog.py
> +            curKb.execute("SELECT rechnung, datum FROM buchung WHERE konto = 'FAUKarte' AND (betrag = ? OR betrag = ? OR betrag = ? OR betrag = ? OR betrag = ? OR betrag = ?) AND datum BETWEEN ? AND
Do we really need the OR query? For float, `abs(betrag - ?) < 1e-4` should work as well, and for text, we should normalize when saving.

2017-05-02 22:22 UTC, BDrescher commented on FabLabKasse/faucardPayment/FAUcardPaymentThread.py
> +        self.amount = amount
Amount has carefully been replaced with amount_cents. This variable is used throughout the whole payment procedure and amount is only used as a Decimal backup. You are definetely right in the point that we want a Decimal and I just not to enforce the usage by float_to_decimal.
At the moment i expect the amount to already be decimal (the prior conversion in faucard.py wasa removed)

2017-05-02 22:26 UTC, BDrescher commented on FabLabKasse/faucardPayment/MagPosLog.py
> +        self.cur.execute("CREATE TABLE IF NOT EXISTS MagPosLog(id INTEGER PRIMARY KEY AUTOINCREMENT, datum, cardnumber INT, amount TEXT, oldbalance INT, newbalance INT, timestamp_payed, status INT, i
The problem is that the database does not store it with unlimited precision as far as i noticed. The amount 2.04999 were therefore cut to be 2.04 ...
The conversion was already done this evening (SQLITE can do that on its own) but not yet pushed to Kasse. I verified the conversion by summing the columns and comparing side by side and have not yet seen any difference in data so far.

The column type TEXT was choosen to copy the structure of kassenbuch, where "betrag" is of type TEXT.

2017-05-02 22:27 UTC, BDrescher commented on FabLabKasse/faucardPayment/faucard.py
>          assert isinstance(amount, (Decimal, float)), "PayupFAUCard: Amount to pay not Decimal or float"
You are correct. Thanks for the notice. As already mentioned this should be happening in FAUcardPaymentThread aswell.

2017-05-02 22:29 UTC, BDrescher commented on FabLabKasse/faucardPayment/generateLog.py
> +            curKb.execute("SELECT rechnung, datum FROM buchung WHERE konto = 'FAUKarte' AND (betrag = ? OR betrag = ? OR betrag = ? OR betrag = ? OR betrag = ? OR betrag = ?) AND datum BETWEEN ? AND
It happened to me that bookings in Kassenbuch had 0 to 4 decimal points. As i moved from float to Decimal I need to check for text equality by ORing.
If we normalize the data (to 0.01/ 0.001) accuracy i could remove the OR clauses.

2017-05-03 17:27 UTC, BDrescher commented
Hello,
I've updated the code again and implemented some improvements mentioned by @mgmax .
Additionally I updated the Dialog to use Decimal aswell to prevent false display and added a function to check the last MagPosLog entry if it was not booked. This could be extended further if desired.
As the check is called before every payment, the coverage should be 100%.

2017-05-03 18:48 UTC, mgmax commented on FabLabKasse/faucardPayment/MagPosLog.py
> +        self.cur.execute("CREATE TABLE IF NOT EXISTS MagPosLog(id INTEGER PRIMARY KEY AUTOINCREMENT, datum, cardnumber INT, amount TEXT, oldbalance INT, newbalance INT, timestamp_payed, status INT, i
okay, that sounds convincing.

2017-05-03 19:36 UTC, mgmax requested changes
As far as I understand it, it looks good, with some minor things to fix.

2017-05-03 19:36 UTC, mgmax commented on FabLabKasse/UI/FAUcardPaymentDialogCode.py
> +        self.amount = float_to_decimal(amount,2)
can't we just pass in amount as Decimal? From a quick look at the code, I'd guess it already is, and we can remove this, (and update `assert isinstance` and `:type amount:` accordingly, and probably remove the import of float_to_decimal)

2017-05-03 19:36 UTC, mgmax commented on FabLabKasse/faucardPayment/FAUcardPaymentThread.py
> +            logging.error(u"CheckTransaction: Buchung für Karte {0} über Betrag {1} EURCENT fehlt".format(value[1], value[2]) )
The code is slightly misleading because all three branches of this `if`-`elif`-`else` lead to `return True`, but only the `elif` contains an explicit `return` statement.

2017-05-03 19:36 UTC, mgmax commented on FabLabKasse/faucardPayment/generateLog.py
> +            curKb.execute("SELECT rechnung, datum FROM buchung WHERE konto = 'FAUKarte' AND (abs(betrag - ?) < 1e-4) AND datum BETWEEN ? AND ? ",(unicode(amount), timestamp, timestamp + timedelta(sec
It is amusing that this SQL statement really works if `betrag` is  column type `TEXT`. Let's consider it a feature of SQLite :-D

2017-05-03 19:36 UTC, mgmax commented on FabLabKasse/faucardPayment/faucard.py
>          :type amount: Decimal float
The `:type:` docs should be updated to match isinstance (for all changes to `isinstance`)

2017-05-03 19:36 UTC, mgmax commented on FabLabKasse/faucardPayment/FAUcardPaymentThread.py
> +            logging.error(u"CheckTransaction: Buchung für Karte {0} über Betrag {1} EURCENT fehlt".format(value[1], value[2]) )
"Buchung fehlt" -> "Buchung im Kassenbuch fehlt"? Die Meldung ist hier nicht so klar, auch nicht was man denn jetzt tun soll.

2017-05-03 19:36 UTC, mgmax commented on FabLabKasse/faucardPayment/MagPosLog.py
> +from ..shopping.backend.abstract import float_to_decimal
unused import?

2017-05-03 19:55 UTC, BDrescher commented on FabLabKasse/faucardPayment/MagPosLog.py
> +from ..shopping.backend.abstract import float_to_decimal
Forgot to remove after usage was removed before commiting

2017-05-03 19:57 UTC, BDrescher commented on FabLabKasse/faucardPayment/FAUcardPaymentThread.py
> +            logging.error(u"CheckTransaction: Buchung für Karte {0} über Betrag {1} EURCENT fehlt".format(value[1], value[2]) )
Thats correct. The return value should only signal if the check could be performed without issues and does not correlate with the fact if a error was found. I updated the documentation and substituted the `return True` with `pass`

2017-05-03 19:57 UTC, BDrescher commented on FabLabKasse/UI/FAUcardPaymentDialogCode.py
> +        self.amount = float_to_decimal(amount,2)
That is right, we can enforce the usage of Decimal

2017-05-07 19:59 UTC, mgmax approved these changes

2017-05-07 20:23 UTC, mgmax commented
Please feel free to merge.

As a side note: I just pushed commit 7b0c1d2 to development which enforces Decimal for the common payment API (not FAU Card specific).

2017-05-08 18:35 UTC, merged