FEATURE: Add client via GUI
fau-fablab/FabLabKasse pull request #161
Opened 2021-10-12 17:19 UTC by mgmax

This adds a GUI equivalent for "kb client create", protected by an administrative PIN.

The list of clients is also protected by this PIN for privacy.

2021-10-24 22:13 UTC, patkan requested changes
Thank you for your work :-)

Mostly stylistic nit-pick (and just a few questions)

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        self.shopping_backend = shopping_backend;
```suggestion
        self.shopping_backend = shopping_backend
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        self.comboBox_client.setVisible(False);
```suggestion
        self.comboBox_client.setVisible(False)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        admin_pin = KeyboardDialog.askText("Admin PIN?", parent=self, hidden_input=True)
```suggestion
        admin_pin = KeyboardDialog.askText(u"Admin PIN?", parent=self, hidden_input=True)
```
Is it intentional not to use a unicode literal here?

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        if admin_pin != "1234":
hardcoded?!

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        username = KeyboardDialog.askText("Kundenkennung (nur a-z 0-9 -) (mind. 5 Zeichen): vorname-nachname oder firma", parent=self) or ""
```suggestion
        username = KeyboardDialog.askText(u"Kundenkennung (nur a-z 0-9 -) (mind. 5 Zeichen): vorname-nachname oder firma", parent=self) or ""
```
again here; unicode?

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        if not re.match(r'^[a-zA-Z0-9_]{5,}$', username):
we do not accept umlauts, correct?

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +            address[i] = KeyboardDialog.askText("Anschrift Zeile " + str(i + 1) + "/4   " + addressLabel[i], parent=self);
depending on whether askText accepts unicode, you should either
* change addressLabel to not contain unicode literals
* make the rest a unicode literal

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        email1 = KeyboardDialog.askText("Email Kunde - Teil VOR dem @", parent=self)
```suggestion
        email1 = KeyboardDialog.askText(u"Email Kunde - Teil VOR dem @", parent=self)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        email2 = KeyboardDialog.askText("Email Kunde - Teil NACH dem @", parent=self)
```suggestion
        email2 = KeyboardDialog.askText(u"Email Kunde - Teil NACH dem @", parent=self)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        comment = KeyboardDialog.askText("Kommentar", parent=self)
```suggestion
        comment = KeyboardDialog.askText(u"Kommentar", parent=self)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        username = username.replace("-", "_");
```suggestion
        username = username.replace("-", "_")
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        username = username.replace(" ", "_");
```suggestion
        username = username.replace(" ", "_")
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +            address[i] = KeyboardDialog.askText("Anschrift Zeile " + str(i + 1) + "/4   " + addressLabel[i], parent=self);
```suggestion
            address[i] = KeyboardDialog.askText(u"Anschrift Zeile " + str(i + 1) + "/4   " + addressLabel[i], parent=self)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        address = "; ".join(address);
```suggestion
        address = "; ".join(address)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        pin = random.randint(1, 9999);
```suggestion
        pin = random.randint(1, 9999)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        DEFAULT_DEBT_LIMIT = 300;
```suggestion
        DEFAULT_DEBT_LIMIT = 300
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +            client_id = self.shopping_backend.add_client(username, email, address, pin, comment, DEFAULT_DEBT_LIMIT);
```suggestion
            client_id = self.shopping_backend.add_client(username, email, address, pin, comment, DEFAULT_DEBT_LIMIT)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +            msgBox.setText(u"Fehler: " + str(e));
```suggestion
            msgBox.setText(u"Fehler: " + str(e))
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        msgBox.setText(u"Bitte notieren: Kundennr " + str(client_id) + " PIN " + str(pin) + ". Fertig.");
```suggestion
        msgBox.setText(u"Bitte notieren: Kundennr " + str(client_id) + " PIN " + str(pin) + ". Fertig.")
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/ClientDialogCode.py
> +        self._reload_clients();
```suggestion
        self._reload_clients()
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/UI/KeyboardDialogCode.py
> +    def __init__(self, parent, question='What: ', hidden_input=False):
```suggestion
    def __init__(self, parent, question=u'What: ', hidden_input=False):
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/config.ini.example
> +client_admin_pin = 1234
I think is not used currently. (Hardcoded instead)

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +import sqlite3
This hasn't been necessary before as the kassenbuch instance itself does not load the dataset but gets it on startup, correct?

Edit: ah ok, slightly different: `Kunde` knows how to access the database?

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +        kunde.name = name;
```suggestion
        kunde.name = name
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +    def add_client(self, name, email, address, pin, comment, debt_limit):
How about a bit of tinfoil hat sanity checks: default value None and handle if None. Or is None an acceptable value for `Kunde` entries?

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +        kunde.email = email;
```suggestion
        kunde.email = email
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +        kunde.adresse = address;
```suggestion
        kunde.adresse = address
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +        kunde.pin = str(pin);
```suggestion
        kunde.pin = str(pin)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +        kunde.kommentar = comment;
```suggestion
        kunde.kommentar = comment
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +        kunde.schuldengrenze = Decimal(debt_limit);
```suggestion
        kunde.schuldengrenze = Decimal(debt_limit)
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +        kunde.telefon = "";
```suggestion
        kunde.telefon = ""
```

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +        except sqlite3.IntegrityError:
Would be slightly more clean to catch this exception in `Kunde` and wrap it into a `Kunde` exception class so that we do not depend on `sqlite3` here. But on the other hand :man_shrugging:

2021-10-24 22:13 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +            raise Exception("Name already exists")
```suggestion
            raise Exception(u"Name already exists")
```

2021-10-25 17:26 UTC, mgmax commented
I fixed these issues, as far as possible with reasonable effort.

2021-10-25 21:40 UTC, patkan commented on FabLabKasse/shopping/backend/legacy_offline_kassenbuch.py
> +            raise Exception("Name already exists")
This one should not be unicode?

2021-10-25 21:42 UTC, patkan commented
> 
> 
> I fixed these issues, as far as possible with reasonable effort.

OK, thank you. It looks good to me now. I currently cannot get the vagrant setup on my machine to run, so unfortunately I haven't run it yet. If you are sure that it is OK, it would be OK for me, otherwise I will try to get my vagrant running again.

2021-10-25 21:42 UTC, patkan approved these changes
See https://github.com/fau-fablab/FabLabKasse/pull/161#issuecomment-951354984 for reference

2021-10-27 16:40 UTC, merged